name: Deploy

on:
  workflow_run:
    workflows:
      - 'ESLint'
    types:
      - 'completed'
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install modules
        run: npm i
      - name: Build static
        run: npm run build
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.RASPBERRY_PASS }}
          name: github-actions
          known_hosts: 'placeholder'

      - name: Adding known_hosts
        run: ssh-keyscan -H ${{ secrets.RASPBERRY_HOST }} >> ~/.ssh/known_hosts

      - name: Sync static
        run: |
          rsync -avz build/ ${{ secrets.RASPBERRY_USER }}@${{ secrets.RASPBERRY_HOST }}:/var/www/html/ttt-online
