name: ESLint

on:
  push:
    paths:
      - "src/**/*.tsx"
      - "src/**/*.ts"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install modules
        working-directory: clients/web
        run: npm i
      - name: Run ESLint
        working-directory: clients/web
        run: npm run lint
